# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/wisdom/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq (1000 4 24 27 30 46 1000TARGET_DEVICE),wisdom)

include $(LOCAL_PATH)/Android-omc.mk

endif
