# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/p205/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),p205)

include $(LOCAL_PATH)/Android-omc.mk

endif
