PRODUCT_PACKAGES += \
    p205_omc_BRI_conf_cscfeature_xml \
    p205_omc_BRI_conf_cscfeature_network_xml \
    p205_omc_BRI_conf_customer_xml \
    p205_omc_BRI_conf_omc_info \
    p205_omc_BRI_etc_BRI_keystrings_dat \
    p205_omc_BRI_etc_byoddeletepackagenames_txt \
    p205_omc_BRI_etc_contents_db \
    p205_omc_BRI_etc_default_application_order_xml \
    p205_omc_BRI_etc_default_workspace_xml \
    p205_omc_BRI_etc_default_workspace_guest_xml \
    p205_omc_BRI_etc_default_workspace_homeonly_xml \
    p205_omc_BRI_etc_enforceskippingpackages_txt \
    p205_omc_BRI_etc_hidden_apks_list_txt \
    p205_omc_BRI_etc_sales_code_dat \
    p205_omc_BRI_opt_appres_json \
    p205_omc_CAM_conf_cscfeature_xml \
    p205_omc_CAM_conf_cscfeature_network_xml \
    p205_omc_CAM_conf_customer_xml \
    p205_omc_CAM_conf_omc_info \
    p205_omc_CAM_etc_CAM_keystrings_dat \
    p205_omc_CAM_etc_byoddeletepackagenames_txt \
    p205_omc_CAM_etc_contents_db \
    p205_omc_CAM_etc_default_application_order_xml \
    p205_omc_CAM_etc_default_workspace_xml \
    p205_omc_CAM_etc_default_workspace_guest_xml \
    p205_omc_CAM_etc_default_workspace_homeonly_xml \
    p205_omc_CAM_etc_enforcedeletepackage_txt \
    p205_omc_CAM_etc_enforceskippingpackages_txt \
    p205_omc_CAM_etc_hidden_apks_list_txt \
    p205_omc_CAM_etc_language_xml \
    p205_omc_CAM_etc_sales_code_dat \
    p205_omc_CPW_conf_cscfeature_xml \
    p205_omc_CPW_conf_cscfeature_network_xml \
    p205_omc_CPW_conf_customer_xml \
    p205_omc_CPW_conf_omc_info \
    p205_omc_CPW_etc_CPW_keystrings_dat \
    p205_omc_CPW_etc_byoddeletepackagenames_txt \
    p205_omc_CPW_etc_contents_db \
    p205_omc_CPW_etc_default_application_order_xml \
    p205_omc_CPW_etc_default_workspace_xml \
    p205_omc_CPW_etc_default_workspace_guest_xml \
    p205_omc_CPW_etc_enforcedeletepackage_txt \
    p205_omc_CPW_etc_enforceskippingpackages_txt \
    p205_omc_CPW_etc_hidden_apks_list_txt \
    p205_omc_CPW_etc_sales_code_dat \
    p205_omc_CSCVersion_txt \
    p205_omc_LAO_conf_cscfeature_xml \
    p205_omc_LAO_conf_cscfeature_network_xml \
    p205_omc_LAO_conf_customer_xml \
    p205_omc_LAO_conf_omc_info \
    p205_omc_LAO_etc_LAO_keystrings_dat \
    p205_omc_LAO_etc_byoddeletepackagenames_txt \
    p205_omc_LAO_etc_contents_db \
    p205_omc_LAO_etc_default_application_order_xml \
    p205_omc_LAO_etc_default_workspace_xml \
    p205_omc_LAO_etc_default_workspace_homeonly_xml \
    p205_omc_LAO_etc_enforcedeletepackage_txt \
    p205_omc_LAO_etc_enforceskippingpackages_txt \
    p205_omc_LAO_etc_hidden_apks_list_txt \
    p205_omc_LAO_etc_language_xml \
    p205_omc_LAO_etc_sales_code_dat \
    p205_omc_LAO_opt_appres_json \
    p205_omc_MYM_conf_cscfeature_xml \
    p205_omc_MYM_conf_cscfeature_network_xml \
    p205_omc_MYM_conf_customer_xml \
    p205_omc_MYM_conf_omc_info \
    p205_omc_MYM_etc_MYM_keystrings_dat \
    p205_omc_MYM_etc_byoddeletepackagenames_txt \
    p205_omc_MYM_etc_contents_db \
    p205_omc_MYM_etc_default_application_order_xml \
    p205_omc_MYM_etc_default_workspace_xml \
    p205_omc_MYM_etc_default_workspace_guest_xml \
    p205_omc_MYM_etc_default_workspace_homeonly_xml \
    p205_omc_MYM_etc_enforcedeletepackage_txt \
    p205_omc_MYM_etc_enforceskippingpackages_txt \
    p205_omc_MYM_etc_hidden_apks_list_txt \
    p205_omc_MYM_etc_language_xml \
    p205_omc_MYM_etc_sales_code_dat \
    p205_omc_MYM_opt_appres_json \
    p205_omc_SW_Configuration_xml \
    p205_omc_THL_conf_cscfeature_xml \
    p205_omc_THL_conf_cscfeature_network_xml \
    p205_omc_THL_conf_customer_xml \
    p205_omc_THL_conf_omc_info \
    p205_omc_THL_etc_THL_keystrings_dat \
    p205_omc_THL_etc_byoddeletepackagenames_txt \
    p205_omc_THL_etc_contents_db \
    p205_omc_THL_etc_default_application_order_xml \
    p205_omc_THL_etc_default_workspace_xml \
    p205_omc_THL_etc_default_workspace_guest_xml \
    p205_omc_THL_etc_default_workspace_homeonly_xml \
    p205_omc_THL_etc_enforceskippingpackages_txt \
    p205_omc_THL_etc_hidden_apks_list_txt \
    p205_omc_THL_etc_language_xml \
    p205_omc_THL_etc_sales_code_dat \
    p205_omc_THL_etc_wifi_cred_conf \
    p205_omc_THL_opt_appres_json \
    p205_omc_XME_conf_cscfeature_xml \
    p205_omc_XME_conf_cscfeature_network_xml \
    p205_omc_XME_conf_customer_xml \
    p205_omc_XME_conf_omc_info \
    p205_omc_XME_etc_XME_keystrings_dat \
    p205_omc_XME_etc_byoddeletepackagenames_txt \
    p205_omc_XME_etc_contents_db \
    p205_omc_XME_etc_default_application_order_xml \
    p205_omc_XME_etc_default_workspace_xml \
    p205_omc_XME_etc_default_workspace_guest_xml \
    p205_omc_XME_etc_default_workspace_homeonly_xml \
    p205_omc_XME_etc_enforceskippingpackages_txt \
    p205_omc_XME_etc_hidden_apks_list_txt \
    p205_omc_XME_etc_language_xml \
    p205_omc_XME_etc_regulatory_info_png \
    p205_omc_XME_etc_sales_code_dat \
    p205_omc_XTC_conf_cscfeature_xml \
    p205_omc_XTC_conf_cscfeature_network_xml \
    p205_omc_XTC_conf_customer_xml \
    p205_omc_XTC_conf_omc_info \
    p205_omc_XTC_etc_XTC_keystrings_dat \
    p205_omc_XTC_etc_byoddeletepackagenames_txt \
    p205_omc_XTC_etc_contact_us_txt \
    p205_omc_XTC_etc_contents_db \
    p205_omc_XTC_etc_default_application_order_xml \
    p205_omc_XTC_etc_default_workspace_xml \
    p205_omc_XTC_etc_default_workspace_guest_xml \
    p205_omc_XTC_etc_default_workspace_homeonly_xml \
    p205_omc_XTC_etc_enforceskippingpackages_txt \
    p205_omc_XTC_etc_general_terms_txt \
    p205_omc_XTC_etc_hidden_apks_list_txt \
    p205_omc_XTC_etc_ntc_image_png \
    p205_omc_XTC_etc_product_warranty_txt \
    p205_omc_XTC_etc_sales_code_dat \
    p205_omc_XTC_etc_warranty_exceptions_txt \
    p205_omc_XTC_opt_appres_json \
    p205_omc_XXV_conf_cscfeature_xml \
    p205_omc_XXV_conf_cscfeature_network_xml \
    p205_omc_XXV_conf_customer_xml \
    p205_omc_XXV_conf_omc_info \
    p205_omc_XXV_etc_XXV_keystrings_dat \
    p205_omc_XXV_etc_byoddeletepackagenames_txt \
    p205_omc_XXV_etc_contents_db \
    p205_omc_XXV_etc_default_application_order_xml \
    p205_omc_XXV_etc_default_workspace_xml \
    p205_omc_XXV_etc_default_workspace_guest_xml \
    p205_omc_XXV_etc_default_workspace_homeonly_xml \
    p205_omc_XXV_etc_enforceskippingpackages_txt \
    p205_omc_XXV_etc_hidden_apks_list_txt \
    p205_omc_XXV_etc_sales_code_dat \
    p205_omc_XXV_opt_appres_json \
    p205_omc_code \
    p205_omc_omc_b2b_list \
    p205_omc_omc_data_json \
    p205_omc_sales_code_dat \
    p205_omc_sales_code_list_dat
